### ISSUE TITLE
question: it seems like golang/tools has a similar package

### ISSUE THREAD

**Issue by scbizu** [fatih/astrewrite#3]
The golang/tools is [here](https://github.com/golang/tools/blob/master/go/ast/astutil/rewrite.go#L43)

Just for curiosity , what's the difference between these two package ? (BTW the Go official package support cursor mode)

Thanks in advance .

**Comment by fatih** [comment]
Hi @scbizu 

That project was written after astrewrite was created. Feel free to use that package instead of this one. Thank you.
